# Generated by Django 4.2.28 on 2026-02-22 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
